# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9ff028135a1fdcd76293e717f0d950977961e0c5eecfe489523c870c1d6e64bdf3424cdff954004a9d220f2d5471775d14475c7ed714ffdead490c5a209c3c5

test:
  secret_key_base: 99e0288fb4ab3c3b675792fe803aa8e8b9c693d382e7718d03aa66a73fe3ceb909ff1bf6d43ce24773d419c581ede2e68371056713ff133e1c0b7f979d34bd9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
